# This file generates the build matrix
# https://zmk.dev/docs/user-setup#build-matrix

include:
  # 左手側: Studio用のスニペットを適用する
  - board: seeeduino_xiao_ble
    shield: atsukey_left
    snippet: studio-rpc-usb-uart

  # 右手側: スニペットなし (これでエラーが回避されます！)
  - board: seeeduino_xiao_ble
    shield: atsukey_right
